### ISSUE TITLE
Symbols Treeview stuck loading

### ISSUE THREAD

**Issue by Gama11** [igbenic/SymbolsTreeview#1]
When I run the command to open the treeview, it just displays a loading bar - there are two exceptions in the dev console:

>command 'vscode.executeDocumentSymbolsProvider' not found: Error: command 'vscode.executeDocumentSymbolsProvider' not found

>Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at checkEditor (C:\Users\\<user\>\\.vscode\extensions\igbenic.symbolstreeview-0.0.6\extension.js:256:14)

**Comment by igbenic** [comment]
Thank you for reporting the issue, 0.0.7 is out with this issue resolved

**Comment by Gama11** [comment]
Thanks, that has indeed fixed it. 👍
