### ISSUE TITLE
"command 'extension.showSymbolsTreeview' not found"

### ISSUE THREAD

**Issue by farcaller** [igbenic/SymbolsTreeview#3]
I'm getting `command 'extension.showSymbolsTreeview' not found` message when I press shift+cmd+a (or select the command from the palette).

Running Symbol Tree View 0.1.5 and VSCode 1.12.2

**Comment by igbenic** [comment]
Hello, thanks for reporting this issue, at the moment I'm not able to reproduce this behavior, could you try reinstalling?

**Comment by farcaller** [comment]
Reinstalling helped, thanks.
