### ISSUE TITLE
Clicking on a symbol opens an empty tab

### ISSUE THREAD

**Issue by farcaller** [igbenic/SymbolsTreeview#7]
Clicking on a symbol opens an empty tab, called "extensions"

![image](https://cloud.githubusercontent.com/assets/693/26278277/4c19368c-3d8e-11e7-89e6-e252bb52453a.png)

Running Symbol Tree View 0.1.5 and VSCode 1.12.2

**Comment by igbenic** [comment]
Hello thank you for reporting this issue, I'll look into it as soon as I get near my PC

**Comment by igbenic** [comment]
Hello, I cannot reproduce this after some testing I did, can you give me some more info, which filetype this happens for, how often this occurs, is it reproducable? Thank you in advance!

**Comment by farcaller** [comment]
`go` and `ts` files, occurs every single time (100% reproducible)

**Comment by mikesmullin** [comment]
also in .lua files

**Comment by mikesmullin** [comment]
i wish we could just get the ctrl+shift+o menu to stay open in a sidebar
