### ISSUE TITLE
PL/SQL symbols are not shown

### ISSUE THREAD

**Issue by Danieleeee** [igbenic/SymbolsTreeview#9]
Hi,
symbols tree work only for file.ts?
Or like symbols in VS CODE, for all language?
I'm using SQL and PLSQL and symbols are not shown.

Thanks.

**Comment by igbenic** [comment]
Hello, thank you for reporting this issue. Well, I'm using symbols that visual studio code provides me with, the idea is that you should have symbol definitions installed for visual studio and then this extension has access to those same symbol definitions.

That said, do you have some symbol definitions for plsql and sql?

**Comment by Danieleeee** [comment]
Yes, I have symbols provided from [plsql-language](https://github.com/zabel-xyz/plsql-language) extension.
This is how it appear:
![schermata 2017-05-24 alle 21 18 12](https://cloud.githubusercontent.com/assets/22749175/26421513/a581703c-40c6-11e7-87be-5e32ebc18eea.png)

**Comment by igbenic** [comment]
Yes, this is definitelly reproducible, I have the same problem, I'll get back to you with a patch in the next version for this problem

**Comment by Danieleeee** [comment]
Thanks
